import "@/assets/styles/app.scss";
import "@/assets/styles/globals.css";
import { Header } from "@/components/layouts/Header";
import { Noto_Sans_JP } from "next/font/google";

const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  preload: true,
});

export const metadata = {
  title: "Next.js Awesome Memo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={NotoSansJP.className}>
        <Header />
        <main>
          <div className="container-sp _mb-2">{children}</div>
        </main>
      </body>
    </html>
  );
}
