import "@/assets/styles/app.scss";
import "@/assets/styles/globals.css";
import { Header } from "@/components/layouts/Header";
import { AppProvider } from "@/providers";
import { Noto_Sans_JP } from "next/font/google";

const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  preload: true,
});

// Pages Routerでは、ページのタイトルやmetaタグ情報はnext/headのHeadコンポーネントで設定していました。
// App Routerでは、metadataオブジェクトをexportすることで設定します。page.jsxもしくはlayout.jsxでexportできます。
export const metadata = {
  title: "Next.js Awesome Memo App",
  description: "Generated by create next app",
};

// Pages Routerにあった_document.jsや_app.jsは廃止され、/appフォルダ直下のlayout.jsxがその代わりになる
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={NotoSansJP.className}>
        <AppProvider>
          <Header />
          <main>
            <div className="container-sp _mb-2">{children}</div>
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
